services:
  # ===================== Backend Service =====================
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  # ===================== Frontend Service =====================
  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

# ===================== Shared Network =====================
networks:
  app-network:
    driver: bridge
