services:
  # ===================== Backend Service =====================
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  # ===================== Frontend Service =====================
  frontend:
    image: nginx:alpine
    container_name: react-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
    networks:
      - app-network


# ===================== Shared Network =====================
networks:
  app-network:
    driver: bridge
